## 1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

In [1]:
import torch

## 2. Create a random tensor with shape (7, 7).

In [3]:
Matrix_x = torch.rand(7,7)
Matrix_x, Matrix_x.shape

(tensor([[0.2375, 0.6200, 0.5698, 0.0545, 0.9904, 0.5016, 0.4993],
         [0.8589, 0.3542, 0.0187, 0.3588, 0.8785, 0.7002, 0.8270],
         [0.2292, 0.2577, 0.8043, 0.2800, 0.4823, 0.7394, 0.2476],
         [0.0072, 0.3569, 0.9595, 0.2892, 0.6757, 0.0786, 0.1925],
         [0.2352, 0.0024, 0.8146, 0.6825, 0.2240, 0.4427, 0.8690],
         [0.3691, 0.8569, 0.0404, 0.9832, 0.6594, 0.9457, 0.8517],
         [0.5437, 0.6377, 0.4768, 0.3290, 0.8068, 0.7793, 0.6150]]),
 torch.Size([7, 7]))

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [4]:
Matrix_y = torch.rand(1,7)
Matrix_y, Matrix_y.shape

(tensor([[0.6340, 0.9731, 0.2756, 0.5935, 0.6411, 0.6426, 0.1145]]),
 torch.Size([1, 7]))

In [5]:
Matrix_x @ Matrix_y.T

tensor([[1.9576],
        [2.2152],
        [1.5966],
        [1.2936],
        [1.3085],
        [2.7905],
        [2.3803]])

In [8]:
torch.matmul(Matrix_x, Matrix_y.T)

tensor([[1.9576],
        [2.2152],
        [1.5966],
        [1.2936],
        [1.3085],
        [2.7905],
        [2.3803]])

## 4. Set the random seed to 0 and do exercises 2 & 3 over again.

In [14]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
Matrix__x = torch.rand(7,7)
print(Matrix_x)

torch.manual_seed(RANDOM_SEED)
Matrix_y = torch.rand(1,7)
print(Matrix_y)

torch.matmul(Matrix_x, Matrix_y.T)

tensor([[0.2375, 0.6200, 0.5698, 0.0545, 0.9904, 0.5016, 0.4993],
        [0.8589, 0.3542, 0.0187, 0.3588, 0.8785, 0.7002, 0.8270],
        [0.2292, 0.2577, 0.8043, 0.2800, 0.4823, 0.7394, 0.2476],
        [0.0072, 0.3569, 0.9595, 0.2892, 0.6757, 0.0786, 0.1925],
        [0.2352, 0.0024, 0.8146, 0.6825, 0.2240, 0.4427, 0.8690],
        [0.3691, 0.8569, 0.0404, 0.9832, 0.6594, 0.9457, 0.8517],
        [0.5437, 0.6377, 0.4768, 0.3290, 0.8068, 0.7793, 0.6150]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.5189],
        [1.8668],
        [1.1583],
        [0.7527],
        [1.0562],
        [2.1946],
        [1.8889]])

In [4]:
import torch

## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [6]:
RANDOM_SEED = 1234
if device == 'cuda':
  torch.cuda.manual_seed(RANDOM_SEED)

## 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [10]:
torch.manual_seed(RANDOM_SEED)
Matrix_a = torch.rand(2,3)

torch.manual_seed(RANDOM_SEED)
Matrix_b = torch.rand(2,3)

print(Matrix_a)
print(Matrix_b)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])


In [12]:
Matrix_a.device, Matrix_b.device

(device(type='cpu'), device(type='cpu'))

In [14]:
Matrix_a = Matrix_a.to(device)
Matrix_b = Matrix_b.to(device)

Matrix_a, Matrix_b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [17]:
mul_matrix = torch.matmul(Matrix_a, Matrix_b.T)
mul_matrix

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

## 8. Find the maximum and minimum values of the output of 7.

In [18]:
torch.min(mul_matrix), mul_matrix.min()

(tensor(0.2161, device='cuda:0'), tensor(0.2161, device='cuda:0'))

In [19]:
torch.max(mul_matrix), mul_matrix.max()

(tensor(0.6287, device='cuda:0'), tensor(0.6287, device='cuda:0'))

## 9. Find the maximum and minimum index values of the output of 7.

In [20]:
torch.argmin(mul_matrix), mul_matrix.argmin()

(tensor(1, device='cuda:0'), tensor(1, device='cuda:0'))

In [21]:
torch.argmax(mul_matrix), mul_matrix.argmax()

(tensor(3, device='cuda:0'), tensor(3, device='cuda:0'))

## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [25]:
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)

tensor_a = torch.rand(1,1,1,10)

# tensor_b = tensor_a[0,0,0,:]
tensor_b = tensor_a.squeeze()

print(tensor_a, tensor_a.shape)
print(tensor_b, tensor_b.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
