In [1]:
import torch

In [2]:
torch.__version__

'1.13.0+cu116'

# Tensor
## Createring tensor

In [3]:
# scalars

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
print(scalar)

tensor(7)


In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
scalar.item

<function Tensor.item>

In [8]:
# vector

vector = torch.tensor([3, 3])
vector

tensor([3, 3])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
[i.item() for i in vector]

[3, 3]

In [12]:
# matrix
MATRIX = torch.tensor([[4, 5],
                       [6, 7]])
MATRIX

tensor([[4, 5],
        [6, 7]])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[1]

tensor([6, 7])

In [16]:
v = [i for i in MATRIX]
v

[tensor([4, 5]), tensor([6, 7])]

In [17]:
for j in v:
  for i in j:
    print(i.item())

4
5
6
7


In [18]:
  # tensor
  TENSOR = torch.tensor([[[1, 2, 3],
                          [5, 6, 7],
                          [9, 10, 11]]])
  TENSOR

tensor([[[ 1,  2,  3],
         [ 5,  6,  7],
         [ 9, 10, 11]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]])

## Random tensor

In [22]:
 random_tensor = torch.rand(3,4)
 random_tensor

tensor([[0.2430, 0.5815, 0.0783, 0.7573],
        [0.0806, 0.4622, 0.7842, 0.8555],
        [0.9293, 0.1121, 0.1859, 0.3986]])

In [23]:
random_tensor.ndim

2

In [24]:
random_image_size_tensor = torch.rand(size = (3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [25]:
print(random_image_size_tensor)

tensor([[[0.0730, 0.0116, 0.1697,  ..., 0.6265, 0.4663, 0.8572],
         [0.9288, 0.6211, 0.2359,  ..., 0.7423, 0.9413, 0.1326],
         [0.4035, 0.2520, 0.9217,  ..., 0.3049, 0.5819, 0.1456],
         ...,
         [0.7432, 0.7375, 0.2164,  ..., 0.2567, 0.6056, 0.5584],
         [0.5533, 0.4239, 0.9096,  ..., 0.2024, 0.6636, 0.8979],
         [0.3557, 0.9761, 0.1364,  ..., 0.2083, 0.0679, 0.2208]],

        [[0.8332, 0.3606, 0.7969,  ..., 0.2987, 0.0482, 0.1628],
         [0.5515, 0.0589, 0.4492,  ..., 0.3045, 0.0718, 0.0182],
         [0.0434, 0.7268, 0.0816,  ..., 0.6087, 0.7968, 0.3442],
         ...,
         [0.1432, 0.5319, 0.0943,  ..., 0.2885, 0.7241, 0.8097],
         [0.7274, 0.3148, 0.4992,  ..., 0.5968, 0.1463, 0.5032],
         [0.6058, 0.6670, 0.7644,  ..., 0.9588, 0.0306, 0.1829]],

        [[0.0395, 0.8026, 0.2016,  ..., 0.2611, 0.4473, 0.5054],
         [0.2600, 0.2006, 0.6299,  ..., 0.3611, 0.8454, 0.2327],
         [0.4950, 0.3763, 0.5196,  ..., 0.6218, 0.3014, 0.

In [26]:
# tensor with all zeros
zeros = torch.zeros(size = (4,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [27]:
# tensor of all ones
ones = torch.ones(size = (3,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [28]:
zeros.dtype

torch.float32

## range of tensor and tensor-like

In [29]:
zero_to_10 = torch.arange(0,11)
zero_to_10

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
any_range = torch.arange(start = 0, end = 1000, step = 64)
any_range

tensor([  0,  64, 128, 192, 256, 320, 384, 448, 512, 576, 640, 704, 768, 832,
        896, 960])

In [31]:
# tensor_like
all_zeros = torch.zeros_like(input = zero_to_10)
all_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## tensor datatype

In [32]:
 float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype = None, # what datatype is tensor (float32, float16, float64)
                                device = None, # what devise is tensor on
                                requires_grad = False) # whether or not to trackgradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_64_tensor = float_32_tensor.type(torch.double)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

# Manipulating Tensor

## Addition, subtraction, Multiplication, Division, Matrix Multiplication

In [36]:
Tensor = torch.tensor([1, 3, 5])
Tensor + 10

tensor([11, 13, 15])

In [37]:
Tensor * 5

tensor([ 5, 15, 25])

In [38]:
Tensor - 4

tensor([-3, -1,  1])

In [39]:
Tensor / 3

tensor([0.3333, 1.0000, 1.6667])

### Matrix multiplication

In [40]:
print(Tensor, "*", Tensor)
print("equal: ", Tensor * Tensor)

tensor([1, 3, 5]) * tensor([1, 3, 5])
equal:  tensor([ 1,  9, 25])


In [41]:
torch.matmul(Tensor, Tensor)

tensor(35)

## shape error in matrix multiplication

In [42]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.3399, 0.2240],
        [1.4280, 1.5298]])

In [43]:
tensor_A = torch.tensor([[2, 3],
                         [4, 6],
                         [8, 9]])
tensor_B = torch.tensor([[3, 4],
                         [6, 8],
                         [9, 12]])

tensor_A @ tensor_B.T

tensor([[ 18,  36,  54],
        [ 36,  72, 108],
        [ 60, 120, 180]])

## min, max, mean and sum in matrix

In [44]:
tensor_A.min()

tensor(2)

In [45]:
tensor_B.max()

tensor(12)

In [46]:
tensor_A.type(torch.float32).mean()

tensor(5.3333)

In [47]:
tensor_B.sum()

tensor(42)

In [48]:
x = torch.arange(0,11)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
torch.min(x), torch.max(x), torch.sum(x)

(tensor(0), tensor(10), tensor(55))

In [50]:
torch.mean(x.type(torch.float32))

tensor(5.)

In [51]:
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [52]:
torch.argmin(tensor_A), tensor_A.argmin()

(tensor(0), tensor(0))

In [53]:
torch.argmax(x), x.argmax()

(tensor(10), tensor(10))

In [54]:
torch.argmax(tensor_B), tensor_B.argmax()

(tensor(5), tensor(5))

### Reshaping, Stacking, Squeezing and Unsqueezing

In [55]:
x.shape, x.reshape(1,11)

(torch.Size([11]), tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]))

In [56]:
z = x.reshape(1,11)

In [57]:
z.shape

torch.Size([1, 11])

In [58]:
y = x.view(1,11)

In [59]:
y[0,5] = 45

In [60]:
x

tensor([ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10])

In [61]:
x_stacked = torch.stack([x, x, x], dim = 0)
x_stacked

tensor([[ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10],
        [ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10],
        [ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10]])

In [62]:
x_stacked = torch.stack([x, x, x], dim = 1)
x_stacked

tensor([[ 0,  0,  0],
        [ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [45, 45, 45],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]])

In [63]:
z, z.shape

(tensor([[ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10]]), torch.Size([1, 11]))

In [64]:
z.squeeze(), z.squeeze().shape

(tensor([ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10]), torch.Size([11]))

In [65]:
z.unsqueeze(dim = 0), z.unsqueeze(dim = 0).shape

(tensor([[[ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10]]]),
 torch.Size([1, 1, 11]))

In [66]:
z.unsqueeze(dim = 1), z.unsqueeze(dim = 1).shape

(tensor([[[ 0,  1,  2,  3,  4, 45,  6,  7,  8,  9, 10]]]),
 torch.Size([1, 1, 11]))

In [67]:
z.unsqueeze(dim = 2), z.unsqueeze(dim = 2).shape

(tensor([[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4],
          [45],
          [ 6],
          [ 7],
          [ 8],
          [ 9],
          [10]]]), torch.Size([1, 11, 1]))

In [68]:
# torch permute

In [69]:
x = torch.rand(size = (3,224,224))
x.shape

torch.Size([3, 224, 224])

In [70]:
x.permute(2, 0, 1).shape

torch.Size([224, 3, 224])

In [71]:
x.permute(2, 1, 0).shape

torch.Size([224, 224, 3])

## Indexing (select data in tensor using index)

In [75]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [77]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
x[0][0]

tensor([1, 2, 3])

In [81]:
x[0][1][2]

tensor(6)

In [83]:
x[:, 1:, 1:]

tensor([[[5, 6],
         [8, 9]]])

## tensor and numpy

In [85]:
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [90]:
torch.arange(1.0, 10.0).dtype

torch.float32

##Reproducibility

In [92]:
# get random out of random
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[5.9059e-01, 3.0857e-01, 9.3433e-01, 8.4918e-01],
        [1.0894e-02, 1.9921e-01, 3.1163e-01, 9.1918e-01],
        [8.4277e-01, 6.6201e-01, 5.6529e-04, 1.0127e-01]])
tensor([[0.5352, 0.6475, 0.8274, 0.5669],
        [0.5981, 0.9609, 0.6178, 0.6299],
        [0.4412, 0.2630, 0.9612, 0.6215]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [100]:
RANDOM_SEED = 64

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.0492, 0.5989, 0.1771, 0.2639],
        [0.4717, 0.8384, 0.1639, 0.1899],
        [0.9971, 0.5516, 0.7827, 0.1247]])
tensor([[0.0492, 0.5989, 0.1771, 0.2639],
        [0.4717, 0.8384, 0.1639, 0.1899],
        [0.9971, 0.5516, 0.7827, 0.1247]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [1]:
!nvidia-smi

Tue Dec 27 06:07:16 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P0    29W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## check cpu with pytorch

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
# setup device agnotic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [6]:
# count number of devices
torch.cuda.device_count()

1

## put tensor on GPU

In [7]:
tensor = torch.tensor([1, 2, 3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [8]:
tensor_to_gpu = tensor.to(device)
tensor_to_gpu

tensor([1, 2, 3], device='cuda:0')

In [10]:
tensor_back_on_cpu = tensor_to_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])